server:
    port: 8080

spring:
    profiles:
        active: prod
    data:
        mongodb:
            uri: mongodb://suayi:vocCemead3@ds041154.mongolab.com:41154/chemshare
            port: 41154
            host: ds041154.mongolab.com
            database: chemshare
            username: suayi
            password: vocCemead3


    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: true

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: chemshare


